GET http://localhost:3000/frames

###
GET http://localhost:3000/frame/32

###
POST http://localhost:3000/frames
Content-Type: application/json

{
    "data":{
        "name": "newFrame",
        "framePhases": [{"name": "phase1"},{"name": "phase2"}],
        "frameInputs": [{"name": "Inp1"},{"name": "Inp2"}]
    }
}


###

DELETE http://localhost:3000/frame/10
Content-Type: application/json


###

POST http://localhost:3000/thing
Content-Type: application/json

{
    "data":{
        "frameId": 36,
        "frameInputs": [{"frameInputId": 74, "text":""},{"frameInputId": 75,"text":""}],
        "framePhases": [{"framePhaseId": 78, "timestamp":""}]
    }
}

###

POST http://localhost:3000/manythings
Content-Type: application/json

{
    "data":[{
        "frameId": 36,
        "frameInputs": [{"frameInputId": 74, "text":""},{"frameInputId": 75,"text":""}],
        "framePhases": [{"framePhaseId": 78, "timestamp":""}]
    }, 
    {
        "frameId": 36,
        "frameInputs": [{"frameInputId": 74, "text":""},{"frameInputId": 75,"text":""}],
        "framePhases": [{"framePhaseId": 78, "timestamp":""}]
    },
    {
        "frameId": 36,
        "frameInputs": [{"frameInputId": 74, "text":""},{"frameInputId": 75,"text":""}],
        "framePhases": [{"framePhaseId": 78, "timestamp":""}]
    }
    ]
}

###

DELETE http://localhost:3000/thing/202
Content-Type: application/json

########

PATCH http://localhost:3000/inputs
Content-Type: application/json

{
    "data":{
        "id": 1042, 
        "text": "first"
    }
    
}

###

PATCH http://localhost:3000/inputs
Content-Type: application/json

{
    "data":{
        "inputs": [
            {
                "id": 40,
                "text": "kelima"
            },
            {
                "id": 41,
                "text": "keenam"  
            }
        ]
    }
}

####

PATCH http://localhost:3000/times
Content-Type: application/json

{
    "data":{
        "id": 187
    }
}

###
