

GET http://localhost:3000/schema

###


POST http://localhost:3000/schema
Content-Type: application/json

{
    "schemeData":{
        "name": "gsfgdsgs",
        "phases": "sme"
    }
}


###

DELETE http://localhost:3000/schema
Content-Type: application/json

{
    "schemeId": 6
}

###

GET http://localhost:3000/thing
Content-Type: application/json

{
    "schemeId": 8
}

###

POST http://localhost:3000/thing
Content-Type: application/json

{
    "schemaId": 7,
    "timestamps": {
        "phases": [
            {
                "position": 1,
                "name": "phaseX",
                "time": "1jun"
            },
            {
                "position": 2,
                "name": "phaseX",
                "time": "2jun"
            }
        ]
    }
}


###

PATCH http://localhost:3000/thing
Content-Type: application/json

{
    "thingId": 4,
    "timestamps": {
        "phases": [
            {
                "position": 1,
                "name": "phasew",
                "time": "1jun"
            },
            {
                "position": 2,
                "name": "phasew",
                "time": "2jun"
            }
        ]
    }
}

###

DELETE http://localhost:3000/thing
Content-Type: application/json

{
    "thingId": 2
}