
POST http://localhost:3000/schema
Content-Type: application/json

{
    "schemeData":{
        "name": "fourthScheme",
        "phases": "sme"
    }
}


###

DELETE http://localhost:3000/schema
Content-Type: application/json

{
    "schemeId": 5
}

###